### ISSUE TITLE
Pl. Provide the Link to Download PDK : cds_ff_mpt_v_0.5 (1.2GB)

### ISSUE THREAD

**Issue by savani138** [chipsalliance/aib-phy-generator#13]
Pl. Provide the Link to Download PDK : cds_ff_mpt_v_0.5 (1.2GB)

**Comment by xinyang2k** [comment]
You need to login to cadence support to get the download. Contact cadence support:
https://registration.cadence.com/CadenceApplicationLoginScreen?appcode=cos&langcode=en

**Comment by savani138** [comment]
But it is cds_ff_mpt_v_1.0 with no layout support in cadence
